{% set name = "setuptools-git-versioning" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6aef5b8bb1cfb953b6b343d27cbfc561d96cf2a2ee23c2e0dd3591042a059921

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - packaging
    - pip
    - python {{ python_min }}
    - setuptools
    - tomli >=2.0.1
  run:
    - packaging
    - python >={{ python_min }}
    - setuptools
    - tomli >=2.0.1

test:
  imports:
    - setuptools_git_versioning
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://setuptools-git-versioning.readthedocs.io
  summary: Use git repo data for building a version number according PEP-440
  dev_url: https://github.com/dolfinus/setuptools-git-versioning
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
