{% set name = "setuptools-git-versioning" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/setuptools-git-versioning-{{ version }}.tar.gz
  sha256: 85b5fbe7bda8e9c24bbd9e587a9d4b91129417f4dd3e11e3c0d5f3f835fc4d4d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - packaging
    - pip
    - python {{ python_min }}
    - setuptools
    - toml >=0.10.2
  run:
    - packaging
    - python >={{ python_min }}
    - setuptools
    - toml >=0.10.2

test:
  imports:
    - setuptools_git_versioning
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://setuptools-git-versioning.readthedocs.io
  summary: Use git repo data for building a version number according PEP-440
  dev_url: https://github.com/dolfinus/setuptools-git-versioning
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
